services:
  db:
    image: postgres:15
    volumes:
      - ./.devdata/postgresql_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
    ports:
      - 5432:5432